import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const manifestText = await readFile(new URL("../content/clients/bkwatch.json", import.meta.url), "utf8");
const manifest = JSON.parse(manifestText);

test("bkWatch manifest is explicitly client-safe and tenant-scoped", () => {
  assert.equal(manifest.clientSafe, true);
  assert.equal(manifest.client.key, "bkwatch");
  assert.equal(manifest.client.route, "/bkwatch");
  assert.doesNotMatch(manifestText, /\/Users\//);
  assert.doesNotMatch(manifestText, /memory\//i);
  assert.doesNotMatch(manifestText, /"password"\s*:/i);
  assert.doesNotMatch(manifestText, /100% accuracy/i);
});

test("Film 1 current state is internally consistent", () => {
  assert.equal(manifest.film.name, "Film 1 - Shaw Integration");
  assert.equal(manifest.film.phase, "Demo production — building selected demo");
  assert.equal(manifest.film.runtime, "22 seconds");
  assert.equal(manifest.film.ideas.length, 9);
  assert.equal(manifest.film.ideas[0].number, "HYBRID");
  assert.equal(manifest.film.ideas[0].title, "Final Demo");
  assert.equal(manifest.film.ideas.reduce((sum, idea) => sum + idea.scenes.length, 0), 30);
  assert.equal(manifest.film.ideas[0].scenes.length, 6);
  assert.equal(manifest.film.ideas.slice(1).every((idea) => idea.scenes.length === 3), true);
  assert.equal(manifest.film.ideas.slice(1).every((idea) => idea.runtime === "15 seconds"), true);
  assert.equal(manifest.film.ideas.every((idea) => idea.scenes.map((scene) => scene.script).join(" ") === manifest.film.script), true);
  assert.equal(manifest.film.approvedMedia, 0);
  assert.equal(manifest.film.ideas[0].recommendation, "Selected production candidate");
  assert.deepEqual(manifest.film.ideas[0].scenes.map((scene) => scene.time), ["Seconds 0–2", "Seconds 3–5", "Seconds 6–10", "Seconds 11–14", "Seconds 15–18", "Seconds 19–22"]);
  assert.match(manifest.film.ideas[0].scenes[1].direction, /Generate the file-like NEW FILING label.*same production pass/);
  assert.equal(manifest.film.comparisonCriteria.some((criterion) => /recommendation/i.test(criterion)), false);
  assert.match(manifest.film.approvals.join(" "), /Shaw approval for Spectrum UI use is secured/);
  assert.doesNotMatch(manifestText, /\bJustin\b/);
  assert.doesNotMatch(manifestText, /NEW FILING[^"\n]*(?:in post|post-produced)/i);
  assert.doesNotMatch(manifestText, /written (?:usage |cross-client video )?permissions?/i);
  assert.doesNotMatch(manifestText, /NEW CLAIM/);
  assert.equal(manifest.metrics.find((metric) => metric.label === "Generation plan").value, "122");
  assert.match(manifest.metrics.find((metric) => metric.label === "Locked voiceover").unit, /122\.7 WPM/);
});

test("product and AI records retain status and provenance", () => {
  assert.equal(manifest.products.length, 5);
  assert.equal(manifest.products.every((product) => product.source && product.state && product.decisions.length), true);
  const categories = new Set(manifest.aiCapabilities.map((item) => item.category));
  for (const required of ["Operations", "Marketing", "Acquisition", "Service", "Analytics", "Compliance", "Film", "Web", "Communications", "Product / workflow"]) {
    assert.equal(categories.has(required), true, `Missing AI category: ${required}`);
  }
  assert.deepEqual(new Set(manifest.aiCapabilities.map((item) => item.status)), new Set(["active", "partial", "not", "unknown"]));
  assert.equal(manifest.aiCapabilities.every((item) => item.source && item.detail), true);
});

test("public homepage contact and canonical route are wired", async () => {
  const home = await readFile(new URL("../pages/home.html", import.meta.url), "utf8");
  const contact = await readFile(new URL("../pages/contact.html", import.meta.url), "utf8");
  const netlify = await readFile(new URL("../netlify.toml", import.meta.url), "utf8");
  const portalHtml = await readFile(new URL("../bkWatch-os.html", import.meta.url), "utf8");
  const portalFunction = await readFile(new URL("../netlify/functions/bkwatch-portal.mjs", import.meta.url), "utf8");
  const css = await readFile(new URL("../public/portal/bkwatch.css", import.meta.url), "utf8");
  const loginCss = await readFile(new URL("../public/portal/bkwatch-login.css", import.meta.url), "utf8");
  const lightTheme = await readFile(new URL("../public/portal/bkwatch-professional-light-20260714.css", import.meta.url), "utf8");
  const loginLightTheme = await readFile(new URL("../public/portal/bkwatch-login-professional-light-20260714.css", import.meta.url), "utf8");
  const darkTheme = await readFile(new URL("../public/portal/bkwatch-dark-mode-20260714.css", import.meta.url), "utf8");
  const loginDarkTheme = await readFile(new URL("../public/portal/bkwatch-login-dark-mode-20260714.css", import.meta.url), "utf8");
  const themeInit = await readFile(new URL("../public/portal/bkwatch-theme-init.js", import.meta.url), "utf8");
  const compactHeaders = await readFile(new URL("../public/portal/bkwatch-compact-headers-20260714.css", import.meta.url), "utf8");
  const logoFrame = await readFile(new URL("../public/portal/bkwatch-logo-white-frame-20260714.css", import.meta.url), "utf8");
  const portalScript = await readFile(new URL("../public/portal/client-portal.js", import.meta.url), "utf8");
  const designMemory = await readFile(new URL("../memory/BKWATCH/DESIGN.md", import.meta.url), "utf8");
  assert.match(contact, /mailto:ceo@thirdi\.net\?subject=Third%20i%20—%20New%20Project%20Inquiry/);
  assert.match(home, /href="\/bkwatch"/);
  assert.match(netlify, /from = "\/bkWatch"[\s\S]*to = "\/bkwatch"[\s\S]*status = 301/);
  assert.match(netlify, /from = "\/bkwatch"[\s\S]*bkwatch-portal/);
  assert.match(netlify, /for = "\/public\/portal\/\*"[\s\S]*Cache-Control = "no-store, max-age=0"/);
  assert.match(portalHtml, /bkwatch-theme-init\.js\?v=20260714-11/);
  assert.match(portalHtml, /bkwatch-professional-light-20260714\.css\?v=20260714-11/);
  assert.match(portalHtml, /bkwatch-dark-mode-20260714\.css\?v=20260714-11/);
  assert.match(portalHtml, /id="theme-toggle"[\s\S]*role="switch"[\s\S]*aria-checked="false"/);
  assert.match(portalHtml, /bkwatch-compact-headers-20260714\.css/);
  assert.match(portalHtml, /bkwatch-logo-white-frame-20260714\.css/);
  assert.doesNotMatch(portalHtml, /bkwatch-(?:blue-black|light-blue|black-blue)-2026071[34]\.css/);
  assert.match(portalHtml, /client-portal\.js\?v=__ASSET_RELEASE__/);
  assert.match(portalHtml, /bkwatch-logo\.png\?v=white-frame-20260714/);
  assert.match(portalFunction, /bkwatch-theme-init\.js\?v=20260714-11/);
  assert.match(portalFunction, /bkwatch-login-professional-light-20260714\.css\?v=20260714-11/);
  assert.match(portalFunction, /bkwatch-login-dark-mode-20260714\.css\?v=20260714-11/);
  assert.match(portalFunction, /bkwatch-logo-white-frame-20260714\.css/);
  assert.doesNotMatch(portalFunction, /bkwatch-(?:login-blue-black|light-blue|login-black-blue)-2026071[34]\.css/);
  assert.match(portalFunction, /const ASSET_RELEASE = "20260722-12"/);
  // The authenticated route now serves the redesigned shell: embedded (private)
  // manifests + live operational config, with the login page unchanged above.
  assert.match(portalFunction, /id="portal-data" type="application\/json"/);
  assert.match(portalFunction, /portal\/core\/app\.js/);
  assert.match(portalFunction, /bkwatch-logo\.png\?v=white-frame-20260714/);
  assert.match(css, /--blue:#2B66AE/);
  assert.match(css, /--black:#214f88/);
  assert.doesNotMatch(css, /color-scheme:dark|bkWatch blue \+ black portal theme/);
  assert.doesNotMatch(loginCss, /color-scheme:dark|bkWatch blue \+ black login theme/);
  assert.match(lightTheme, /body,[\s\S]*\.workspace \{[\s\S]*background: #fff;[\s\S]*color: #214f88/);
  assert.match(lightTheme, /\.sidebar,[\s\S]*\.topbar \{[\s\S]*background: #fff;[\s\S]*color: #2b66ae/);
  assert.match(lightTheme, /\.primary-nav a\[aria-current="page"\] \{[\s\S]*background: #2b66ae;[\s\S]*color: #fff/);
  assert.match(lightTheme, /\.page-head h1,[\s\S]*\.section-head h2,[\s\S]*\.page-head \.eyebrow,[\s\S]*\.section-head a \{[\s\S]*color: #2b66ae/);
  assert.match(lightTheme, /\.hero-panel,[\s\S]*\.voiceover \{[\s\S]*background: #2b66ae;[\s\S]*color: #fff/);
  assert.match(lightTheme, /\.metric-card \.metric-value,[\s\S]*\.voiceover blockquote \{[\s\S]*color: #fff/);
  assert.match(lightTheme, /\.status-active \{[\s\S]*background: #0d5238;[\s\S]*color: #dff5e9/);
  assert.match(lightTheme, /\.status-partial \{[\s\S]*background: #5a4309;[\s\S]*color: #fff1c2/);
  assert.match(lightTheme, /\.status-not \{[\s\S]*background: #6c2926;[\s\S]*color: #ffe4e1/);
  assert.match(lightTheme, /\.status-unknown \{[\s\S]*background: #344b5c;[\s\S]*color: #e5edf2/);
  assert.match(lightTheme, /\.page-actions \.status \{[\s\S]*border: 0;[\s\S]*box-shadow: none/);
  assert.match(lightTheme, /\.page-actions \.status-active \{[\s\S]*background: #eaf7f0;[\s\S]*color: #147a48/);
  assert.match(lightTheme, /\.page-actions \.status-partial \{[\s\S]*background: #fff6db;[\s\S]*color: #8b6200/);
  assert.match(lightTheme, /\.page-actions \.status-not \{[\s\S]*background: #fff0ef;[\s\S]*color: #a33128/);
  assert.match(lightTheme, /\.page-actions \.status-unknown \{[\s\S]*background: #edf1f3;[\s\S]*color: #5d6870/);
  assert.match(loginLightTheme, /body \{[\s\S]*background: #fff;[\s\S]*color: #214f88/);
  assert.match(loginLightTheme, /\.login-card \{[\s\S]*background: #2b66ae;[\s\S]*color: #fff/);
  assert.match(loginLightTheme, /\.login-form input \{[\s\S]*background: #fff;[\s\S]*color: #214f88/);
  assert.match(loginLightTheme, /\.login-form button \{[\s\S]*background: #fff;[\s\S]*color: #2b66ae/);
  assert.match(darkTheme, /\.theme-toggle \{[\s\S]*background: rgba\(43, 102, 174, 0\.08\);[\s\S]*color: #2b66ae/);
  assert.match(darkTheme, /html\[data-theme="dark"\] \.status-active \{[\s\S]*background: #0b2d22;[\s\S]*color: #8bcbaa/);
  assert.match(darkTheme, /html\[data-theme="dark"\] \.status-partial \{[\s\S]*background: #34290d;[\s\S]*color: #d7bb70/);
  assert.match(darkTheme, /html\[data-theme="dark"\] \.status-not \{[\s\S]*background: #341918;[\s\S]*color: #e39992/);
  assert.match(darkTheme, /html\[data-theme="dark"\] \.status-unknown \{[\s\S]*background: #222b32;[\s\S]*color: #b4c1ca/);
  assert.match(darkTheme, /html\[data-theme="dark"\][\s\S]*background: #080d14/);
  assert.match(darkTheme, /\.hero-panel,[\s\S]*\.voiceover \{[\s\S]*linear-gradient\(#0b0f14, #0b0f14\) padding-box,[\s\S]*linear-gradient\(135deg, #79c4f5 0%, #2b66ae 100%\) border-box/);
  assert.match(darkTheme, /\.button,[\s\S]*\.scene-index a \{[\s\S]*linear-gradient\(135deg, #79c4f5 0%, #2b66ae 100%\)/);
  assert.match(darkTheme, /\.theme-toggle\[aria-checked="true"\][\s\S]*translateX\(16px\)/);
  assert.match(loginDarkTheme, /html\[data-theme="dark"\] \.login-card \{[\s\S]*#0b0f14[\s\S]*#79c4f5[\s\S]*#2b66ae/);
  assert.match(themeInit, /const storageKey = "bkwatch-theme"/);
  assert.match(themeInit, /document\.documentElement\.dataset\.theme = theme/);
  assert.match(portalScript, /window\.localStorage\.setItem\(themeStorageKey, nextTheme\)/);
  assert.match(portalScript, /themeToggle\.setAttribute\("aria-checked", String\(darkMode\)\)/);
  assert.match(designMemory, /Primary Blue \| `#2B66AE`/);
  assert.match(designMemory, /#79C4F5` → `#2B66AE/);
  assert.match(logoFrame, /background: #fff/);
  assert.match(logoFrame, /border-radius: 12px/);
  assert.match(logoFrame, /padding: 10px 12px/);
  assert.match(logoFrame, /\.brand-block \{[\s\S]*padding-left: 0;[\s\S]*padding-right: 0/);
  assert.match(logoFrame, /\.brand-block img \{[\s\S]*width: 100%;[\s\S]*max-width: none/);
  assert.match(compactHeaders, /data-page-spacing="compact"[\s\S]*padding-top: 36px/);
  assert.match(compactHeaders, /\.page-head \.eyebrow \{[\s\S]*margin: 0 0 8px/);
  assert.match(compactHeaders, /max-width: 820px[\s\S]*padding-top: 26px/);
  assert.match(portalScript, /main\.dataset\.pageSpacing = isFilm1Route \? "film1" : "compact"/);
  assert.match(portalScript, /path\.startsWith\(ideaPrefix\)/);
  assert.doesNotMatch([css, loginCss, lightTheme, loginLightTheme].join("\n"), /#2d333b|#79c4f5|color-scheme:\s*dark/i);
  assert.doesNotMatch([css, loginCss, lightTheme, loginLightTheme, darkTheme, loginDarkTheme, designMemory].join("\n"), /#0869b2/i);
  assert.match(portalScript, /derived: "Sourced count"/);
  assert.doesNotMatch(portalScript, /Derived from sourced counts/);
  assert.doesNotMatch(css, /filter:brightness/);
});

test("project hero and primary button presentation contracts are enforced", async () => {
  const cardComponents = await readFile(new URL("../public/portal/components/cards.js", import.meta.url), "utf8");
  const mediaComponents = await readFile(new URL("../public/portal/components/media.js", import.meta.url), "utf8");
  const filmPresentation = await readFile(new URL("../public/portal/pages/film-presentation.js", import.meta.url), "utf8");
  const libraryPage = await readFile(new URL("../public/portal/pages/library.js", import.meta.url), "utf8");
  const projectDetail = await readFile(new URL("../public/portal/pages/project-detail.js", import.meta.url), "utf8");
  const projectsPage = await readFile(new URL("../public/portal/pages/projects.js", import.meta.url), "utf8");
  const portalComponentsCss = await readFile(new URL("../public/portal/styles/portal-components.css", import.meta.url), "utf8");
  const portalPagesCss = await readFile(new URL("../public/portal/styles/portal-pages.css", import.meta.url), "utf8");
  const portalShellCss = await readFile(new URL("../public/portal/styles/portal-shell.css", import.meta.url), "utf8");
  const feedComponents = await readFile(new URL("../public/portal/components/feed.js", import.meta.url), "utf8");
  const homePage = await readFile(new URL("../public/portal/pages/home.js", import.meta.url), "utf8");
  const libraryRecord = await readFile(new URL("../public/portal/pages/library-record.js", import.meta.url), "utf8");
  const search = await readFile(new URL("../public/portal/core/search.js", import.meta.url), "utf8");
  const portalApp = await readFile(new URL("../public/portal/core/app.js", import.meta.url), "utf8");
  const dataJs = await readFile(new URL("../public/portal/core/data.js", import.meta.url), "utf8");

  assert.doesNotMatch(projectDetail, /next:\s*p\.nextMilestone/);
  assert.doesNotMatch(mediaComponents, /ip-next|next\s*=/);
  assert.doesNotMatch(filmPresentation, /next:\s*s\.status/);
  assert.doesNotMatch(filmPresentation, /statusLabel\(s\.status\)/);
  assert.doesNotMatch(projectDetail, /creative-direction-title/);
  assert.match(projectDetail, /comparisonCriteria\.filter\(\(criterion\) => !\/recommendation\/i\.test\(criterion\)\)/);
  assert.doesNotMatch(projectDetail, /<th>Recommendation<\/th>/);
  assert.doesNotMatch(projectDetail, /esc\(i\.recommendation/);
  assert.match(projectDetail, /pc-meta creative-direction-badges/);
  assert.match(projectDetail, /statusLabel\("Locked", "ok", true\)/);
  assert.match(projectDetail, /<span class="chip"><span class="control-content">/);
  assert.match(projectDetail, /reading muted comparison-criteria/);
  const scriptPosition = projectDetail.indexOf('${p.script ?');
  const scopePosition = projectDetail.indexOf('${scope}');
  const selectedDemoPosition = projectDetail.indexOf('${renderSelectedDemo(p, film)}');
  const creativeDirectionsPosition = projectDetail.indexOf('${film ?', selectedDemoPosition);
  assert.ok(scriptPosition >= 0 && scriptPosition < scopePosition && scopePosition < selectedDemoPosition && selectedDemoPosition < creativeDirectionsPosition);
  assert.equal(projectDetail.match(/\$\{scope\}/g)?.length, 1);
  assert.match(projectsPage, /id="new-project-btn"[\s\S]*?<span class="control-content">/);
  assert.match(projectsPage, /<div class="new-project-action"><button/);
  assert.match(projectsPage, /<div class="page filter-page">/);
  assert.match(libraryPage, /<div class="page filter-page">/);
  assert.match(cardComponents, /opticalCenter \? `<span class="control-content">/);
  assert.match(cardComponents, /pc-meta project-card-badges[^\n]*statusLabel\(p\.statusLabel \|\| p\.status, undefined, true\)[^\n]*<span class="chip"><span class="control-content">\$\{esc\(p\.projectType\)\}/);
  assert.match(portalComponentsCss, /\.project-card-badges \.status,[\s\S]*?\.project-card-badges \.chip \{[^}]*height: 28px;[^}]*padding-block: 0;[^}]*line-height: 1;[^}]*align-items: center;[^}]*justify-content: center;/);
  assert.match(portalComponentsCss, /\.creative-direction-badges \{ margin-top: 0; \}/);
  assert.match(portalComponentsCss, /\.creative-direction-badges \.status,[\s\S]*?\.creative-direction-badges \.chip \{[^}]*height: 24px;[^}]*padding-block: 0;[^}]*line-height: 1;[^}]*align-items: center;[^}]*justify-content: center;/);
  assert.match(portalComponentsCss, /\.in-production \{ --ip-composition-shift: 11\.7%;[^}]*\}/);
  assert.match(portalApp, /values\.startsWith\("567\.071 665\.431"\)[\s\S]*567\.071 669\.431[\s\S]*animation\.remove\(\)/);
  assert.match(portalComponentsCss, /\.in-production \.ip-figure \{[^}]*top: calc\(50% - var\(--ip-composition-shift\)\);[^}]*transform: translate\(-50%, -50%\);/);
  assert.match(portalComponentsCss, /\.in-production \.ip-cap \{[^}]*bottom: calc\(12px \+ var\(--ip-composition-shift\)\);/);
  assert.doesNotMatch(portalComponentsCss, /\.ip-next/);
  assert.match(portalPagesCss, /\.project-preview \.ip-badge \{ font-size: var\(--fs-body\); \}/);
  assert.doesNotMatch(portalComponentsCss, /\.in-production \.ip-badge \{[^}]*font-size: var\(--fs-body\)/);
  assert.match(portalPagesCss, /\.comparison-criteria \{ padding-block: var\(--space-2\); \}/);
  assert.match(portalPagesCss, /\.filter-page \.page-lede \{ margin-bottom: var\(--space-2\); \}/);
  assert.match(portalPagesCss, /\.filter-page \.filters \{ margin-bottom: 0; \}/);
  assert.match(portalPagesCss, /\.filter-page \.filters \+ \.section \{ margin-top: var\(--space-2\); \}/);
  assert.match(portalPagesCss, /\.new-project-action \{ padding-block: var\(--space-3\) var\(--space-4\); \}/);
  assert.match(portalPagesCss, /#new-project-btn \{ margin: 0; \}/);
  assert.match(portalShellCss, /\.control-content \{[^}]*display: inline-flex;[^}]*align-items: center;[^}]*transform: translateY\(-1px\);/);
  assert.match(portalShellCss, /\.btn\.btn-primary \{[\s\S]*?color: #000000;[\s\S]*?\}/);
  assert.match(portalShellCss, /\.btn\.btn-primary:hover \{[\s\S]*?color: #ffffff;[\s\S]*?\}/);
  assert.match(portalShellCss, /\.btn:hover \{[^}]*text-decoration: none;/);
  assert.match(cardComponents, /export const cardAction/);
  assert.match(cardComponents, /cardAction\("Open project"\)/);
  assert.match(projectDetail, /cardAction\("Open direction"\)/);
  assert.match(projectDetail, /project-value-strip/);
  assert.match(projectDetail, /label: "hours"/);
  assert.match(projectDetail, /label: "weeks active"/);
  assert.match(projectDetail, /label: "deliverables ready"/);
  assert.match(projectDetail, /label: "selected demo scenes"/);
  assert.match(filmPresentation, /idea\.mediaPolicy !== "none"/);
  assert.match(filmPresentation, /media preview spaces appear only after a direction is selected for demo production/);
  assert.match(filmPresentation, /return \{ redirect: href\(`\/projects\/\$\{p\.slug\}#selected-demo`\) \}/);
  assert.match(projectDetail, /function renderSelectedDemo/);
  assert.match(projectDetail, /This locked HYBRID no longer has a separate direction page/);
  assert.doesNotMatch(projectDetail, /renderPromotedProduction/);
  assert.doesNotMatch(projectDetail, /<h2>Open blockers<\/h2>/);
  assert.doesNotMatch(projectDetail, /commentsWithProjectBlockers/);
  assert.doesNotMatch(libraryPage, /commentsWithProjectBlockers/);
  assert.match(dataJs, /kind: "comment",[\s\S]*blocker: true/);
  assert.doesNotMatch(feedComponents, /c\.readonly/);
  assert.match(homePage, /cardAction\("Open roadmap"\)/);
  assert.match(libraryRecord, /cardAction\("View record"\)/);
  assert.match(search, /View result/);
  assert.match(portalComponentsCss, /\.card-link \{[^}]*color: inherit;[^}]*text-decoration: none;/);
  assert.match(portalComponentsCss, /\.card-action \{[\s\S]*?background: var\(--accent-gradient\); color: #000;/);
  assert.match(portalComponentsCss, /\.card-link:hover \.card-action \{ background: var\(--ink-900\); color: #fff; \}/);
  assert.match(portalPagesCss, /\.project-value-strip \{[^}]*grid-template-columns: repeat\(4,/);
});

test("Value & Results gates efficiency evidence and preserves tenant privacy", async () => {
  const valuePage = await readFile(new URL("../public/portal/pages/value-results.js", import.meta.url), "utf8");
  const homePage = await readFile(new URL("../public/portal/pages/home.js", import.meta.url), "utf8");
  const projectDetail = await readFile(new URL("../public/portal/pages/project-detail.js", import.meta.url), "utf8");
  const portalPagesCss = await readFile(new URL("../public/portal/styles/portal-pages.css", import.meta.url), "utf8");
  const metricsScript = await readFile(new URL("../scripts/portal/extract-metrics.mjs", import.meta.url), "utf8");

  assert.match(valuePage, /completed >= threshold && projects\.length >= threshold/);
  assert.match(valuePage, /class="efficiency-readiness"/);
  assert.match(valuePage, /class="efficiency-chart"/);
  assert.match(valuePage, /Only verified actual efficiency is labeled/);
  assert.match(valuePage, /future-value-item/);
  assert.match(valuePage, /class="section momentum-section"/);
  assert.match(valuePage, /\$\{futureMomentum\(invoicing\)\}/);
  assert.match(valuePage, /What stays private/);
  assert.doesNotMatch(valuePage, /financialSection|Financial summary|outcomeRow|>Outcomes<|Future value record/);
  assert.doesNotMatch(valuePage, /crossClientSection|crossClientTraining|614 hours|Shaw Conference|Amplify/);
  assert.match(metricsScript, /actualHoursPerMinute: 150/);
  assert.match(metricsScript, /actualHoursPerMinute: 120/);
  assert.match(metricsScript, /completedProjectCount: 0/);
  assert.match(portalPagesCss, /\.vr-hero \{[^}]*grid-template-columns:/);
  assert.match(portalPagesCss, /\.momentum-future \{[^}]*margin-top:/);
  assert.match(portalPagesCss, /\.privacy-columns \{[^}]*grid-template-columns: 1fr 1fr/);
  assert.match(homePage, /ai-value-label">hours<\/span>/);
  assert.match(homePage, /ai-value-label">capabilities<\/span>/);
  assert.match(projectDetail, /label: "hours"/);
});
